#trigger:
#  - main

trigger:
  branches:
    exclude: [ "main" ]
# the above can also be written as below
#    - main
  tags:
    include: [ "*" ]

pool: slave


variables:
  COMPONENT: 'frontend'

resources:
  repositories:
    - repository: templates
      type: github
      name: GurukaYadav/roboshop-azure-devops-templates
      endpoint: GurukaYadav

stages:
  - template: nginx.yml@templates